### ISSUE TITLE
Make the proper documentation in Readme

### ISSUE THREAD

**Issue by haseeb-xd** [haseeb-xd/Covid19-Tracker#1]

**Comment by Dorcastunmise** [comment]
Hello @haseeb-xd , I'll like to work on this

**Comment by Radiosnack** [comment]
Can you brief on what exactly we should do in readme section ?

**Comment by haseeb-xd** [comment]
For example: Improving `About` section

**Comment by Dorcastunmise** [comment]
@haseeb-xd please I'll like to know the dependencies or packages you used for this project. I need to include the installation process in the file.

**Comment by Dorcastunmise** [comment]
Hey @haseeb-xd...... a PR has been sent.
